### PR TITLE
Translations: Thai

### PR DESCRIPTION
**Pull request by b2nkuu**
Hi,
This for thai (ไทย) translation,

Some sentence is not perfect, but is useful.
I will revise later, when un smooth when play in app.
thank a lots.

### CODE REVIEW

**Comment by mytonwalletorg** [comment]
Hello, thanks for your contribution. Are you planning to add more improvements here? @B2NKUU

**Comment by B2NKUU** [comment]
Yes, i will check it again, 
and send source completed in next days.
Thanks.

**Comment by Mazi48** [comment]
Hello, thank you for your message. I don't know about these games and I
invested 29 Tether on August 29 to my wallet account. After contacting
wallet support, they told me the way to return the money to the account,
but I still can't figure it out. Please help me in this matter.  Thank you,
the cost will be paid

در تاریخ شنبه ۱۱ مه ۲۰۲۴،‏ ۷:۱۵ B2NKUU ***@***.***> نوشت:

**Comment by B2NKUU** [comment]
Hi. 
Translate is be enough to merge.
Thanks.

**Comment by mytonwalletorg** [comment]
> Hi. Translate is be enough to merge. Thanks.

Merged, thank you!

Please, share your TON address for a contribution reward from MyTonWallet ❤️

**Review by mytonwalletorg — APPROVED** [review]

**Comment by b2nkuu** [comment]
> > Hi. Translate is be enough to merge. Thanks.
> 
> Merged, thank you!
> 
> Please, share your TON address for a contribution reward from MyTonWallet ❤️

This is my wallet address 
b2nkuu-wallet.ton [UQAIt0LUCrK7DLb13q6qgzUMWiG7piTbYNhR4KkzfsFelRMS]
Thanks

**Comment by b2nkuu** [comment]
Yes, @mytonwalletorg.
Very Thank for your reward.

Next time when I have time, I will seek out and contribute in your projects again.
❤️❤️❤️

**Comment by mytonwalletorg** [comment]
Thank you too @b2nkuu. ♥️

**Comment by Mazi48** [comment]
Hello, my Tether deposit has not been counted yet!!??  Does it take time?!!!  What's going on? Thank you for your follow-up

**Comment by Mazi48** [comment]
`برگشتی صورت نگرفته!!!!`

**Comment by mytonwalletorg** [comment]
> Hello, my Tether deposit has not been counted yet!!?? Does it take time?!!! What's going on? Thank you for your follow-up

Hi,

Please refer to https://t.me/MyTonWalletSupport.

Please, be patient, we are overbooked at the moment and will respond within 72 hours. Thanks for understanding.

**Pull request merged**
