### PR TITLE
[Translations] add Ukrainian language

### PR DESCRIPTION
**Pull request by KL0nLutiy**
[Translations] add Ukrainian language

### CODE REVIEW

**Review by 2530607 — APPROVED** [review]

**Review by 2530607 — APPROVED** [review]

**Comment by mytonwalletorg** [comment]
@KL0nLutiy Thanks a lot for this contribution! 👍 We will merge it soon.

**Comment by mytonwalletorg** [comment]
@KL0nLutiy Please, provide your TON wallet address for a reward from MyTonWallet 🎊

**Comment by KL0nLutiy** [comment]
@mytonwalletorg UQBBbsH3ulXJQ00ZtIjKOh726h8FhYMhxEWHLl4UZ6FhZoXR

**Review by o123666 — COMMENTED** [review]
@

**Pull request merged**
